#!/usr/bin/sh
1. Write a script that asks the user for their age, then compares that age to a variable called retirement_age. If the age They entered is greater, print out a message telling them should be retired. Otherwise, tell them that They are still quite young.
	. Make sure you correctly handle the case where the user simply presses ENTER and doesn't type in an age

2. Write a script that reads the name of a directory from the keyboard and then checks to see if the name They entered is indeed a directory, and can be written to (try to do this test on one line). If all is okay, the script should create a file in the given directory called hello. (handle the case where the user simply presses ENTER without entering a directory name).
