#!/usr/bin/sh
#	The above line causes this script to be run using the Bourne Shell (sh)
#########################################################################################
#
#	Script to maintain a contacts database.
#
#########################################################################################

#
#	Define the name of the file
#
fname=names.dat

#
#	Read in the contact details from the keyboard
#
echo "Please enter the following contact details:"
echo
echo -e "Given name: \c"
read name
echo -e "   Surname: \c"
read surname
echo -e "   Address: \c"
read address
echo -e "      City: \c"
read city
echo -e "     State: \c"
read state
echo -e "	Zip: \c"
read zip

#
#	Write the details to the text file
#
echo $name:$surname:$address:$city:$state:$zip >> $fname

#
#	Show what's currently in the file
#
(
	echo
	echo Here are the current contacts in the database:
	echo 
	cat $fname
) | more

#
#	And display how many there are
#
echo
echo There are `cat $fname | wc -l` contacts in the database
