#!/usr/bin/sh
echo -e "Please enter the name of a directory: \c"
read dir

while [ ! -d "$dir" ]
do
	echo "$dir is not a directory"
	echo -e "Please try again: \c"
	read dir
done

echo Congratulations: $dir is a directory!
