#!/usr/bin/sh
#
#	First, the user's name
#
echo -e "Please enter your name: \c"
read name
echo Name: $name > details.out

#
#	Next, the user's address
#
echo -e "Please enter your address: \c"
read address
echo Address: $address >> details.out		# note: APPENDING!

#
#	Next, the user's phone number
#
echo -e "Please enter your phone number: \c"
read phone
echo Phone: $phone >> details.out

#
#	Finally, display the message about the filename
echo Thank you. The details have been stored in the file \"details.out\"
